import os
import time
from datetime import datetime

now = datetime.now()
stamp = now.strftime("%d/%m/%Y %H:%M:%S")
div = '---------------------------------------------'


def sbat():
    print('Starting job start.bat')
    print(div)
    print('Server will by default start with no gui only cli.')

    aram = int(input('How many gigabytes of ram? :'))
    jarname = str(input('What is the .jar name? (e.g., server.jar): '))

    with open('start.bat', 'w') as sbf:
        sbf.write('@echo off\ncls\n:start\n')
        sbf.write(f'java -Xmx{aram}G -Xms{aram}G -jar {jarname} nogui\n')
        sbf.write('echo (%time%) Server closed/crashed... restarting!\ngoto start')

    print('start.bat job finished!')


def eulat():
    print('Starting job eula.txt')
    with open('eula.txt', 'w') as euf:
        euf.write(f'#EULA generated by MCST. {stamp}\n')
        euf.write('eula=true\n')
        print('Eula set to true')

    print('eula.txt job finished!')


def servers(question="[y/n]", strict=True):
    print('Start server?')
    x = input(f"{question.strip(' ')} ").lower()
    if x in {"yes", "y"}:
        os.startfile('start.bat')
    elif x in {"no", "n"}:
        print('Exiting program.')
        time.sleep(5)
        exit()
    else:
        return servers(strict=strict)


def sprop():
    print('Starting job server.properties')

    wl = str(input('white listed true/false:'))
    hc = str(input('Hardcore mode true/false:'))
    mp = int(input('Max players (e.g., 10): '))
    pvp = str(input('PVP true/false: '))
    motd = str(input('Server Motd: '))

    with open('server.properties', 'w') as spf:
        spf.write('#server.properties generated with MCST\n')
        spf.write(f'#server.properties created on {stamp}\n')
        spf.write('enable-jmx-monitoring=false\n')

        spf.write('\n#rcon settings\n')
        spf.write('enable-rcon=false\n')
        spf.write('rcon.port=25575\n')
        spf.write('broadcast-rcon-to-ops=true\n')
        spf.write('rcon.password=\n')

        spf.write('\n#level Settings\n')
        spf.write('level-seed=\n')
        spf.write("level-type=minecraft\\:normal\n")
        spf.write('level-name=world\n')
        spf.write('allow-nether=true\n')
        spf.write('spawn-npcs=true\n')
        spf.write('spawn-animals=true\n')
        spf.write('spawn-monsters=true\n')
        spf.write('spawn-protection=16\n')
        spf.write('difficulty=easy\n')
        spf.write('generate-structures=true\n')
        spf.write(f'hardcore={hc.lower()}\n')
        spf.write(f'pvp={pvp.lower()}\n')
        spf.write('gamemode=survival\n')
        spf.write('max-world-size=29999984\n')
        spf.write('generator-settings={}\n')
        spf.write('max-build-height=256\n')
        spf.write('view-distance=10\n')
        spf.write('simulation-distance=10\n')
        spf.write('max-tick-time=60000\n')
        spf.write('max-chained-neighbor-updates=1000000\n')

        spf.write('\n#resource pack\n')
        spf.write('resource-pack-sha1=\n')
        spf.write('resource-pack=\n')
        spf.write('resource-pack-id=\n')
        spf.write('resource-pack-prompt=\n')
        spf.write('require-resource-pack=false\n')
        spf.write('initial-disabled-packs=\n')
        spf.write('initial-enabled-packs=vanilla\n')

        spf.write('\n#server settings\n')
        spf.write('server-ip=\n')
        spf.write('server-port=25565\n')
        spf.write('query.port=25565\n')
        spf.write('enable-query=false\n')
        spf.write(f'max-players={mp}\n')
        spf.write(f'white-list={wl.lower()}\n')
        spf.write('enforce-whitelist=false\n')
        spf.write('enforce-secure-profile=true\n')
        spf.write('use-native-transport=true\n')
        spf.write('enable-status=true\n')
        spf.write('sync-chunk-writes=true\n')
        spf.write('prevent-proxy-connections=false\n')
        spf.write('entity-broadcast-range-percentage=100\n')
        spf.write('rate-limit=0\n')
        spf.write('broadcast-console-to-ops=true\n')
        spf.write('log-ips=true\n')
        spf.write('function-permission-level=2\n')
        spf.write('text-filtering-config=\n')
        spf.write(f'motd={motd}\n')

        spf.write('\n#player settings\n')
        spf.write('force-gamemode=false\n')
        spf.write('online-mode=true\n')
        spf.write('op-permission-level=4\n')
        spf.write('announce-player-achievements=true\n')
        spf.write('enable-command-block=false\n')
        spf.write('allow-flight=false\n')
        spf.write('hide-online-players=false\n')
        spf.write('player-idle-timeout=0\n')

    print('server.properties job finished')


print('Starting program.')
print(div)
eulat()
print(div)
sbat()
print(div)
sprop()
print(div)
servers()
